jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/JadeSerfaty/efficient_coding_model.git

  ComputeRowCount:
    needs:
      - CloneRepo
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      image: python:3.8-slim
      script: |
        pip install pandas
        data_path='/data/mock/rating_data.csv'
        row_count=$(python -c "import pandas as pd; print(len(pd.read_csv('${data_path}')))")
        echo $row_count > /data/efficient_coding_model/row_count.txt

  ProcessRows:
    needs:
      - ComputeRowCount
      - CloneRepo
    resources:
      instance-type: C5
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      image: python:3.8-slim
      script: |
        pip install pandas
        pip install -r /data/efficient_coding_model/requirements.txt
        row_count=$(cat /data/efficient_coding_model/row_count.txt)
        for idx in $(seq 0 $(($row_count - 1))); do
          python /data/efficient_coding_model/dummy_model.py $idx
        done
